config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users, only: %i[index destroy new create] do
      get 'change_password', to: 'users#change_password', as: :change_password
      patch 'update_password', to: 'users#update_password'
    end
    get 'user/current', to: 'users#show_current'
    resources :bes, only: [:index, :edit, :update]do
      collection do
        get 'filter_by_loaibe'
        get 'chart'
      end
    end
    resources :tuyencaps, only: [:index]
  end
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :roles do
    delete :bulk_delete, on: :collection
  end
  resources :tuyencaps
  root 'bes#index'
  resources :bes do
    member do
      delete :destroy
    end
  end
  resources :duongongs do
    collection do
      get 'routes'
    end
    member do
      delete 'destroy_route'
    end
  end
  resources :tuyencaps do
    collection do
      post 'create_from_map'
    end
    member do
      post 'add_connections'
      post 'remove_connections'
    end
  end
  resources :users, only: [:show] do
    get 'change_password', to: 'users#change_password', as: :change_password
    patch 'update_password', to: 'users#update_password'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/tuyencap.rb
class Tuyencap < ApplicationRecord
  has_many :tuyen_cap_duong_ongs
  has_many :duongongs, through: :tuyen_cap_duong_ongs
  validates :ten_tuyen, presence: { message: 'Không được để trống tên tuyến.' },
                        uniqueness: { message: 'đã tồn tại.' }
  validates :diembatdau, presence: true
  validates :diemketthuc, presence: true

  has_many :tuyencap_bes, dependent: :destroy
  has_many :bes, through: :tuyencap_bes
end

app/controllers/admin/tuyencaps_controller.rb
module Admin
  class TuyencapsController < ApplicationController
    def index
      # Group thông tin dữ liệu theo `ten_tuyen`
      @grouped_tuyencap_bes = TuyencapBe.includes(:tuyencap, :be_id_dau, :be_id_cuoi)
                                         .all.group_by { |tc| tc.tuyencap.ten_tuyen }
      # Tính tổng số tuyến cáp
      @total_routes = @grouped_tuyencap_bes.keys.count
    end
  end
end

app/controllers/tuyencaps_controller.rb
class TuyencapsController < ApplicationController
  before_action :set_tuyencap, only: %i[show edit update destroy remove_connections]
  before_action :authenticate_user!
  
  # GET /tuyencaps or /tuyencaps.json
  def index
    @tuyencaps = Tuyencap.all
    @bes = Be.all
    # @tuyencaps = Tuyencap.all.includes(:tuyencap_bes)
    respond_to do |format|
      format.html
      format.json { render json: @tuyencaps.as_json(include: { tuyencap_bes: { include: %i[be_id_dau be_id_cuoi] } }) }
    end
  end

  # GET /tuyencaps/1 or /tuyencaps/1.json
  def show; end

  # GET /tuyencaps/new
  def new
    @tuyencap = Tuyencap.new
  end

  # GET /tuyencaps/1/edit
  def edit; end

  # POST /tuyencaps or /tuyencaps.json
  # def create
  #   @tuyencap = Tuyencap.new(tuyencap_params)

  #   respond_to do |format|
  #     if @tuyencap.save
  #       format.html { redirect_to @tuyencap, notice: 'Tuyencap was successfully created.' }
  #       format.json { render :show, status: :created, location: @tuyencap }
  #     else
  #       format.html { render :new, status: :unprocessable_entity }
  #       format.json { render json: @tuyencap.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  def create
    @tuyencap = Tuyencap.new(tuyencap_params)

    if @tuyencap.save
      create_tuyencap_bes(params[:be_ids])
      redirect_to @tuyencap, notice: 'Tuyến cáp đã được tạo thành công.'
    else
      @bes = Be.all
      render :new
    end
  end

  # PATCH/PUT /tuyencaps/1 or /tuyencaps/1.json
  def update
    respond_to do |format|
      if @tuyencap.update(tuyencap_params)
        format.html { redirect_to @tuyencap, notice: 'Tuyencap was successfully updated.' }
        format.json { render :show, status: :ok, location: @tuyencap }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tuyencap.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tuyencaps/1 or /tuyencaps/1.json
  def destroy
    @tuyencap.destroy

    respond_to do |format|
      format.html { redirect_to tuyencaps_path, status: :see_other, notice: 'Tuyến cáp đã bị xóa thành công.' }
      format.json { head :no_content }
    end
  end

  # def create_from_map
  #   @tuyencap = Tuyencap.new(tuyencap_params)

  #   if @tuyencap.save
  #     be_ids = params[:be_ids].split(',')
  #     if be_ids.size >= 2
  #       be_ids.each_cons(2) do |be_id_dau, be_id_cuoi|
  #         TuyencapBe.create(tuyencap: @tuyencap, be_id_dau_id: be_id_dau, be_id_cuoi_id: be_id_cuoi)
  #       end
  #     end

  #     @tuyencap = Tuyencap.includes(tuyencap_bes: %i[be_id_dau be_id_cuoi]).find(@tuyencap.id)

  #     render json: {
  #       success: true,
  #       message: 'Tuyến cap đã được tạo thành công.',
  #       tuyencap: @tuyencap,
  #       tuyencap_id: @tuyencap.id
  #     }
  #   else
  #     render json: { success: false, message: @tuyencap.errors.full_messages }
  #   end
  # end

  def create_from_map
    @tuyencap = Tuyencap.new(tuyencap_params)

    if @tuyencap.save
      be_ids = params[:be_ids].split(',')
      if be_ids.size >= 2
        be_ids.each_cons(2) do |be_id_dau, be_id_cuoi|
          TuyencapBe.create(tuyencap: @tuyencap, be_id_dau_id: be_id_dau, be_id_cuoi_id: be_id_cuoi)
        end
      end

      @tuyencap = Tuyencap.includes(tuyencap_bes: %i[be_id_dau be_id_cuoi]).find(@tuyencap.id)

      render json: {
        success: true,
        message: 'Tuyến cap đã được tạo thành công.',
        tuyencap: @tuyencap.as_json(include: { tuyencap_bes: { include: %i[be_id_dau be_id_cuoi] } })
      }
    else
      render json: { success: false, message: @tuyencap.errors.full_messages }
    end
  end

  def add_connections
    @tuyencap = Tuyencap.find(params[:id])
    be_ids = params[:be_ids].split(',')
  
    if be_ids.size >= 2
      be_ids.each_cons(2) do |be_id_dau, be_id_cuoi|
        TuyencapBe.create(tuyencap: @tuyencap, be_id_dau_id: be_id_dau, be_id_cuoi_id: be_id_cuoi)
      end
      render json: { success: true, message: "Đã thêm đường nối thành công tại tuyến: #{@tuyencap.ten_tuyen}" }
    else
      render json: { success: false, message: 'Vui lòng chọn ít nhất hai BEs để thêm đường nối!' }
    end
  end

  def remove_connections
    be_ids = params[:be_ids].split(',')
    
    TuyencapBe.where(tuyencap: @tuyencap, be_id_dau_id: be_ids, be_id_cuoi_id: be_ids).destroy_all

    render json: {
      success: true,
      message: 'Đường nối đã được xóa thành công.',
      tuyencap: @tuyencap.as_json(include: { tuyencap_bes: { include: %i[be_id_dau be_id_cuoi] } })
    }
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_tuyencap
    @tuyencap = Tuyencap.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def tuyencap_params
    params.permit(:ten_tuyen, :phanloai, :dvquanly, :diembatdau, :diemketthuc, be_ids: [])
  end
end

app/helpers/admin/tuyencaps_helper.rb
module Admin::TuyencapsHelper
end

app/helpers/tuyencaps_helper.rb
module TuyencapsHelper
end

app/views/tuyencaps/_control.html.erb
<div id="tuyen-cap-form-container">
  <div class="controls">
    <%= form_with url: create_from_map_tuyencaps_path, method: :post, local: true, id: 'tuyencap-form' do |form| %>
      <div class="form-group">
        <%= form.label :ten_tuyen, "Tên Tuyến", class: 'sr-only' %>
        <%= form.text_field :ten_tuyen, id: 'tuyen-cap-ten', class: 'form-control mr-2', placeholder: 'Nhập Tên Tuyến' %>
      </div>
      <div class="form-group">
        <%= form.label :diembatdau, "Tên điểm bắt đầu", class: 'sr-only' %>
        <%= form.text_field :diembatdau, id: 'diembatdau_cap', class: 'form-control mr-2', placeholder: 'Nhập điểm bắt đầu' %>
      </div>
      <div class="form-group">
        <%= form.label :diemketthuc, "Tên điểm kết thúc", class: 'sr-only' %>
        <%= form.text_field :diemketthuc, id: 'diemketthuc_cap', class: 'form-control mr-2', placeholder: 'Nhập điểm kết thúc' %>
      </div>
      <div>
        <div class="form-group">
          <%= form.label :phanloai, "Phân Loại", class: 'sr-only' %>
          <%= form.select :phanloai, 
                          options_for_select([
                            ["Chọn phân loại", ""], 
                            ["Cáp 4 Fo (ngầm hoặc treo) (có bọc chống gặm nhấm hoặc không)", "Cáp 4 Fo (ngầm hoặc treo) (có bọc chống gặm nhấm hoặc không)"],
                            ["Cáp 8 Fo (ngầm hoặc treo) (có bọc chống gặm nhấm hoặc không)", "Cáp 8 Fo (ngầm hoặc treo) (có bọc chống gặm nhấm hoặc không)"],
                            ["Cáp 12 Fo (ngầm hoặc treo) (có bọc chống gặm nhấm hoặc không)", "Cáp 12 Fo (ngầm hoặc treo) (có bọc chống gặm nhấm hoặc không)"],
                            ["Cáp 24 Fo (ngầm hoặc treo) (có bọc chống gặm nhấm hoặc không)", "Cáp 24 Fo (ngầm hoặc treo) (có bọc chống gặm nhấm hoặc không)"],
                            ["Cáp 48 Fo (ngầm hoặc treo) (có bọc chống gặm nhấm hoặc không)", "Cáp 48 Fo (ngầm hoặc treo) (có bọc chống gặm nhấm hoặc không)"],
                            ["Cáp 96 Fo (ngầm hoặc treo) (có bọc chống gặm nhấm hoặc không)", "Cáp 96 Fo (ngầm hoặc treo) (có bọc chống gặm nhấm hoặc không)"]
                          ]), 
                          { class: 'form-control mr-2' } %>
        </div>
      </div>
      <div>
        <div class="form-group">
          <%= form.label :dvquanly, "Đơn Vị Quản Lý", class: 'sr-only' %>
          <%= form.select :dvquanly, 
                          options_for_select([
                            ["Chọn Đơn Vị Quản Lý", ""], 
                            ["Trung tâm IID", "Trung tâm IID"],
                            ["Trung tâm đèn THGT", "Trung tâm đèn THGT"],
                            ["VNPT", "VNPT"],
                            ["Viettel", "Viettel"],
                            ["FPT", "FPT"]
                          ]), 
                          { class: 'form-control mr-2' }
          %>
        </div>
      </div>
      <div>
        <%= form.hidden_field :be_ids, id: 'be-ids-field' %>
      </div>
      <div>
        <div class="row mb-2">
          <div class="col">
            <button type="submit" id="create-tuyencap" class="btn btn-primary">Lưu</button>
          </div>
          <div class="col">
            <button type="button" id="cancel-route" class="btn btn-danger">Hủy</button>
          </div>
        </div>
        <button type="button" id="hide-route" class="btn btn-dark">Ẩn Khung</button>
      </div>
    <% end %>
  </div>
</div>
<div class="comineterb">
  <button id="create-new-btn" class="btn btn-success" style="text-align: center; font-size: 20px;">Tạo mới</button>
  <button id="delete-changes-btn" class="btn btn-warning" style="text-align: center; font-size: 20px; display: none;">Xóa</button>
  <button id="save-changes-btn" class="btn btn-danger" style="text-align: center; font-size: 20px; display: none;">Thay đổi</button>
  <button id="hide-routes" class="btn btn-secondary w-100" style="text-align: center; font-size: 20px; display: none;">Ẩn tuyến cáp</button>
    <button id="show-all-routes" onclick="showAllRoutes()" class="btn btn-primary w-100" style="text-align: center; font-size: 20px;">Hiển thị(<span id="route-count">0</span>)</button>
  <div class="row mb-2">
    <div class="col">
      <button onclick="zoomIn()" style="text-align: center; font-size: 20px;">+</button>
    </div>
    <div class="col">
      <button onclick="zoomOut()" style="text-align: center; font-size: 20px;">-</button>
    </div>
  </div>
</div>
<div id="tuyen-cap-list" style="display: none;">
   <div class="show-list-tuyencap">
    <button onclick="closeList()" style="text-align: center; background-color: red; width: 20%;">X</button>
    <% @tuyencaps.each do |tuyencap| %>
      <button onclick="showRoute(<%= tuyencap.id %>)"><%= tuyencap.ten_tuyen %></button>
    <% end %>
  </div>
</div>

app/views/tuyencaps/_form.html.erb
<%= form_with(model: tuyencap) do |form| %>
  <% if tuyencap.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tuyencap.errors.count, "error") %> prohibited this tuyencap from being saved:</h2>

      <ul>
        <% tuyencap.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :ten_tuyen, style: "display: block" %>
    <%= form.text_field :ten_tuyen %>
  </div>

  <div>
    <%= form.label :phanloai, style: "display: block" %>
    <%= form.text_field :phanloai %>
  </div>

  <div>
    <%= form.label :dvquanly, style: "display: block" %>
    <%= form.text_field :dvquanly %>
  </div>

  <div>
    <%= form.label :diembatdau, style: "display: block" %>
    <%= form.text_field :diembatdau %>
  </div>

  <div>
    <%= form.label :diemketthuc, style: "display: block" %>
    <%= form.text_field :diemketthuc %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tuyencaps/_tuyencap.html.erb
<div id="<%= dom_id tuyencap %>">
  <p>
    <strong>Ten tuyen:</strong>
    <%= tuyencap.ten_tuyen %>
  </p>

  <p>
    <strong>Phanloai:</strong>
    <%= tuyencap.phanloai %>
  </p>

  <p>
    <strong>Dvquanly:</strong>
    <%= tuyencap.dvquanly %>
  </p>

  <p>
    <strong>Diembatdau:</strong>
    <%= tuyencap.diembatdau %>
  </p>

  <p>
    <strong>Diemketthuc:</strong>
    <%= tuyencap.diemketthuc %>
  </p>

</div>

app/views/tuyencaps/edit.html.erb
<h1>Editing tuyencap</h1>

<%= render "form", tuyencap: @tuyencap %>

<br>

<div>
  <%= link_to "Show this tuyencap", @tuyencap %> |
  <%= link_to "Back to tuyencaps", tuyencaps_path %>
</div>

app/views/tuyencaps/new.html.erb
<h1>New tuyencap</h1>

<%= render "form", tuyencap: @tuyencap %>

<br>

<div>
  <%= link_to "Back to tuyencaps", tuyencaps_path %>
</div>

app/views/tuyencaps/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @tuyencap %>

<div>
  <%= link_to "Edit this tuyencap", edit_tuyencap_path(@tuyencap) %> |
  <%= link_to "Back to tuyencaps", tuyencaps_path %>

  <%= button_to "Destroy this tuyencap", @tuyencap, method: :delete %>
</div>